name: Maven CICD
on:
  push:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        id: mavn-build
        run: |
          mvn --version
          mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_SECRET }}
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Download the Packages
        run: |
          curl ${{ env.URL }} \
            -H "Authorization: Bearer ${{ secrets.PACKAGES_SECRET }}" \
            -L \
            -O
        env:
          URL: "https://maven.pkg.github.com/cgifed/simple-java-maven-app/com/mycompany/app/my-app/1.0-SNAPSHOT/my-app-1.0-SNAPSHOT.jar"
      - name: Deploying to Dev
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEV_VM_PRIVATE_KEY }}
          port: "22"
          source: "${{ env.FILENAME }}"
          target: "/tmp"
        env:
          HOST: "3.86.108.186"
          USERNAME: "ec2-user"
          FILENAME: "my-app-1.0-SNAPSHOT.jar"


