name: Maven CICD
on:
  push:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        id: mavn-build
        run: |
          mvn --version
          mvn -B -DskipTests clean package
      - name: Verification
        run: |
          ls -latr
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Checking the path
        run: ls -latr
