name: "Using my Maven Action"
on:
  push:
  workflow_dispatch:
jobs:
  CI:
    runs-on: 'maven'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Perform the Build
        uses: cgifed/maven-action@main
        with:
          version: '3.8.6'