name: Self hosted runner test
on:
  push:
  workflow_dispatch:
jobs:
  testing-self-hosted-runner:
    runs-on: maven
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Printing the hostname
        run: hostname
