name: Maven Tests
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  test-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        id: mavn-build
        run: |
          mvn --version
          mvn clean package
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_SECRET }}
